[settings]
domain = "github.com"
owner = "cli"
repo = "cli"

[platforms.macos-aarch64]
name_pattern = "macOS_arm64.zip"
strip_prefix = "gh_$VERSION_macOS_arm64"
add_prefix = "sysroot"

[platforms.macos-x86_64]
name_pattern = "macOS_amd64.zip"
strip_prefix = "gh_$VERSION_macOS_amd64"
add_prefix = "sysroot"

[platforms.windows-aarch64]
name_pattern = "windows_arm64.zip"
strip_prefix = "gh_$VERSION_windows_amd64"
add_prefix = "sysroot"

[platforms.windows-x86_64]
name_pattern = "windows_amd64.zip"
strip_prefix = "gh_$VERSION_windows_amd64"
add_prefix = "sysroot"

[platforms.linux-aarch64]
name_pattern = "linux_arm64.tar.gz"
strip_prefix = "gh_$VERSION_linux_arm64"
add_prefix = "sysroot"

[platforms.linux-x86_64]
name_pattern = "linux_amd64.tar.gz"
strip_prefix = "gh_$VERSION_linux_amd64"
add_prefix = "sysroot"
