[settings]
domain = "github.com"
owner = "microsoft"
repo = "vcpkg-tool"

[platforms.macos-aarch64]
name_pattern = "aarch64-apple-darwin.zip"
add_prefix = "sysroot/bin"

[platforms.macos-x86_64]
name_pattern = "x86_64-apple-darwin.zip"
add_prefix = "sysroot/bin"

[platforms.windows-aarch64]
name_pattern = "aarch64-pc-windows-msvc.zip"
add_prefix = "sysroot/bin"

[platforms.windows-x86_64]
name_pattern = "x86_64-pc-windows-msvc.zip"
add_prefix = "sysroot/bin"

[platforms.linux-aarch64]
name_pattern = "aarch64-unknown-linux-gnu.tgz"
add_prefix = "sysroot/bin"

[platforms.linux-x86_64]
name_pattern = "x86_64-unknown-linux-gnu.tgz"
add_prefix = "sysroot/bin"
