[settings]
domain = "github.com"
owner = "google"
repo = "flatbuffers"

[platforms.macos-aarch64]
name_pattern = "Mac.flatc.binary"
add_prefix = "sysroot/bin"

[platforms.macos-x86_64]
name_pattern = "MacIntel.flatc.binary"
add_prefix = "sysroot/bin"


[platforms.windows-x86_64]
name_pattern = "Windows.flatc.binary"
add_prefix = "sysroot/bin"

[platforms.linux-x86_64]
name_pattern = "Linux.flatc.binary.clang"
add_prefix = "sysroot/bin"
